Set MASShortcut build architecture to 64-bit
My release build was failing because of this error:

    error: -fobjc-arc is not supported with fragile abi

Set MASShortcut to force 64-bit architectures because it uses ARC and
from what I understand ARC can only be used on 64-bit.